name: Compilation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - {compiler: gcc, version: 13}
          - {compiler: intel, version: '2025.0'}
          - {compiler: nvidia-hpc, version: '25.1'}
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: "Install OpenMPI"
        if: matrix.toolchain.compiler == 'gcc'
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: 'openmpi'

      - name: "Install Intel MPI"
        if: matrix.toolchain.compiler == 'intel'
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: 'intelmpi'
        
      - name: "Setup Fortran compiler"
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: "Setup MPI compiler wrapper (GNU)"
        if: matrix.toolchain.compiler == 'gcc'
        run: |
          echo "MPI_COMPILER=mpif90" >> "$GITHUB_ENV"

      - name: "Setup MPI compiler wrapper (Intel)"
        if: matrix.toolchain.compiler == 'intel'
        run: |
          echo "MPI_COMPILER=mpiifx" >> "$GITHUB_ENV"

      - name: Setup MPI compiler wrapper (NVIDIA)
        if: matrix.toolchain.compiler == 'nvidia-hpc'
        run: |
          echo "MPI_COMPILER=/opt/nvidia/Linux_x86_64/hpc_sdk/2025/comm_libs/mpi/bin/mpif90" >> "$GITHUB_ENV"

      - name: Install NetCDF-C
        run: |
          sudo apt-get -y install libnetcdf-dev
      
      - name: Checkout NetCDF-Fortran repository
        if: matrix.toolchain.compiler != 'gcc'
        uses: actions/checkout@v2
        with:
          repository: Unidata/netcdf-fortran
          ref: v4.6.2
          path: netcdf-fortran

      - name: Compile NetCDF-Fortran
        if: matrix.toolchain.compiler != 'gcc'
        run: |
          cd netcdf-fortran
          cmake -DCMAKE_Fortran_COMPILER=${{ env.FC }}
          make -j 2
          sudo make install

      - name: Install NetCDF-Fortran
        if: matrix.toolchain.compiler == 'gcc'
        run: |
          sudo apt-get -y install libnetcdff-dev

      - name: Compile
        run: |
          mkdir build
          cd build
          FC=${{ env.MPI_COMPILER}} cmake -DCMAKE_BUILD_TYPE=DEBUG ..
          make
